# Generated by Django 5.0.3 on 2024-04-01 12:45

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_recette_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='photo',
            field=models.ImageField(default='img4.jpg', upload_to=pages.models.filepath),
        ),
    ]
