# Generated by Django 5.0.4 on 2024-05-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_recette_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='recipes_images'),
        ),
    ]
