# Generated by Django 5.0.4 on 2024-05-27 03:17

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_recette_user_crea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='nom',
            field=models.CharField(max_length=100, validators=[pages.models.validate_name]),
        ),
    ]
