# Generated by Django 5.0.4 on 2024-05-27 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_recette_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='description',
            field=models.TextField(validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only aphanumeric characters are allowed.')]),
        ),
    ]
