# Generated by Django 5.0.4 on 2024-05-27 03:31

import django.core.validators
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_recette_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='nom',
            field=models.CharField(max_length=100, validators=[pages.models.validate_name, django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only aphanumeric characters are allowed.')]),
        ),
    ]
