# Generated by Django 5.0.3 on 2024-03-31 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recette',
        ),
    ]
